Repository Vizzuality/fora, pull requests merged in 2022-09, with the labels that each got.

#1 Lefthook
  client/.eslintrc.js
  client/package.json
  client/yarn.lock
  lefthook.yml
Labels: ready-to-review, front-end

#5 feat: AWS S3 env variables
  backend/ENV_VARS.md
  backend/Gemfile
  backend/Gemfile.lock
  backend/README.md
  backend/config/appsignal.yml
  backend/config/storage.yml
Labels: back-end

#6 Config: config basePath
  client/.env.default
  client/README.md
  client/next.config.js
  client/src/containers/footer/component.tsx
  client/src/containers/home/hero/component.tsx
  client/src/containers/home/how/component.tsx
  client/src/containers/home/invest/component.tsx
  client/src/containers/home/join/component.tsx
  client/src/containers/home/what/component.tsx
Labels: documentation, ready-to-review, front-end

#9 Config: config basePath
  client/.env.default
  client/README.md
  client/public/data/regions.json
  client/src/containers/footer/component.tsx
  client/src/containers/header/component.tsx
  client/src/containers/meta-icons/component.tsx
Labels: ready-to-review, front-end
